"""
Crochet tracker sync server.

Each user has a random "sync key" generated by the client (a UUIDv4-ish string).
That key is the credential — anyone holding it can read/write that user's data.
The server stores one JSON blob per key in SQLite and merges client uploads
last-write-wins per project (by `updatedAt`).

Quick start:
    cd server
    python3 -m venv .venv && . .venv/bin/activate
    pip install -r requirements.txt
    uvicorn server:app --host 0.0.0.0 --port 8000

Optional env vars:
    CROCHET_DB=/path/to/crochet.db    SQLite file (default: ./crochet.db)
    CROCHET_STATIC=/path/to/frontend  Serve frontend files from here
                                      (default: parent dir; the index.html lives there)
    CROCHET_NO_STATIC=1               API only, no static file serving
    CROCHET_HOST=0.0.0.0              uvicorn host when run via `python server.py`
    CROCHET_PORT=8000                 uvicorn port

Nginx example (proxying both API and static through one location):
    location /crochet/ {
        proxy_pass http://127.0.0.1:8000/;
        proxy_set_header Host $host;
    }
"""
import json
import os
import re
import sqlite3
import time
from contextlib import contextmanager
from pathlib import Path
from typing import Optional

from fastapi import FastAPI, Header, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import FileResponse
from pydantic import BaseModel, Field

DB_PATH = os.environ.get("CROCHET_DB", "crochet.db")
STATIC_DIR = os.environ.get("CROCHET_STATIC", str(Path(__file__).resolve().parent.parent))
NO_STATIC = os.environ.get("CROCHET_NO_STATIC") == "1"

MAX_PROJECTS = 1000
MAX_BLOB_BYTES = 10 * 1024 * 1024

KEY_RE = re.compile(r"^[A-Za-z0-9_-]{16,256}$")


@contextmanager
def db():
    conn = sqlite3.connect(DB_PATH)
    conn.row_factory = sqlite3.Row
    try:
        yield conn
        conn.commit()
    finally:
        conn.close()


def init_db():
    with db() as conn:
        conn.execute(
            """
            CREATE TABLE IF NOT EXISTS users (
              sync_key   TEXT PRIMARY KEY,
              data       TEXT NOT NULL,
              updated_at INTEGER NOT NULL
            )
            """
        )


init_db()


class Project(BaseModel):
    id: str = Field(min_length=1, max_length=128)
    name: str = Field(max_length=256)
    rawText: str = Field(max_length=200_000)
    cursor: dict
    createdAt: Optional[int] = None
    lastOpenedAt: Optional[int] = None
    updatedAt: int
    deletedAt: Optional[int] = None


class SyncRequest(BaseModel):
    projects: list[Project] = Field(max_length=MAX_PROJECTS)


class SyncResponse(BaseModel):
    projects: list[Project]


app = FastAPI(title="Crochet sync")

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["GET", "POST", "OPTIONS"],
    allow_headers=["X-Sync-Key", "Content-Type"],
)


def validate_key(key: Optional[str]) -> str:
    if not key or not KEY_RE.match(key):
        raise HTTPException(status_code=400, detail="Invalid sync key")
    return key


def load_projects(key: str) -> list[dict]:
    with db() as conn:
        row = conn.execute(
            "SELECT data FROM users WHERE sync_key = ?", (key,)
        ).fetchone()
    if not row:
        return []
    try:
        return json.loads(row["data"]).get("projects", [])
    except json.JSONDecodeError:
        return []


def save_projects(key: str, projects: list[dict]):
    data = json.dumps({"projects": projects}, ensure_ascii=False)
    if len(data.encode("utf-8")) > MAX_BLOB_BYTES:
        raise HTTPException(status_code=413, detail="Sync payload too large")
    now = int(time.time() * 1000)
    with db() as conn:
        conn.execute(
            """
            INSERT INTO users (sync_key, data, updated_at) VALUES (?, ?, ?)
            ON CONFLICT(sync_key) DO UPDATE SET
              data = excluded.data, updated_at = excluded.updated_at
            """,
            (key, data, now),
        )


def merge(server_projects: list[dict], client_projects: list[dict]) -> list[dict]:
    """Last-write-wins per project id, comparing updatedAt."""
    by_id: dict[str, dict] = {p["id"]: p for p in server_projects}
    for cp in client_projects:
        existing = by_id.get(cp["id"])
        if not existing or cp.get("updatedAt", 0) > existing.get("updatedAt", 0):
            by_id[cp["id"]] = cp
    return list(by_id.values())


@app.post("/api/sync", response_model=SyncResponse)
def sync(payload: SyncRequest, x_sync_key: str = Header(default=None)):
    key = validate_key(x_sync_key)
    merged = merge(load_projects(key), [p.model_dump() for p in payload.projects])
    save_projects(key, merged)
    return {"projects": merged}


@app.get("/api/health")
def health():
    return {"ok": True}


if not NO_STATIC:
    SAFE_NAME = re.compile(r"^[A-Za-z0-9._-]+$")

    @app.get("/")
    def index():
        path = Path(STATIC_DIR) / "index.html"
        if not path.is_file():
            raise HTTPException(404)
        return FileResponse(path)

    @app.get("/{filename}")
    def static_file(filename: str):
        if not SAFE_NAME.match(filename):
            raise HTTPException(404)
        path = Path(STATIC_DIR) / filename
        if not path.is_file():
            raise HTTPException(404)
        return FileResponse(path)


if __name__ == "__main__":
    import uvicorn

    uvicorn.run(
        app,
        host=os.environ.get("CROCHET_HOST", "127.0.0.1"),
        port=int(os.environ.get("CROCHET_PORT", "8000")),
    )
